"""initial schema

Revision ID: 9dffa68fb792
Revises: 
Create Date: 2026-08-25 00:32:48.065120
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9dffa68fb792'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_call_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('node', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('operation', sa.Text(), nullable=False),
    sa.Column('loop_index', sa.SmallInteger(), nullable=False),
    sa.Column('cost_inr', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('units', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='research'
    )
    op.create_index('ix_api_call_log_run_provider', 'api_call_log', ['run_id', 'provider'], unique=False, schema='research')
    op.create_table('evidence',
    sa.Column('evidence_id', sa.Text(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('loop_index', sa.SmallInteger(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('verbatim_quote', sa.Text(), nullable=True),
    sa.Column('quote_start', sa.Integer(), nullable=True),
    sa.Column('quote_end', sa.Integer(), nullable=True),
    sa.Column('grounding', sa.Text(), nullable=False),
    sa.Column('pinpoint', sa.Text(), nullable=True),
    sa.Column('citation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('supports_issues', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('jurisdiction', sa.Text(), nullable=False),
    sa.Column('court_level', sa.Text(), nullable=False),
    sa.Column('binding_strength', sa.Text(), nullable=False),
    sa.Column('authority_tier', sa.SmallInteger(), nullable=False),
    sa.Column('llm_confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('evidence_id'),
    schema='research'
    )
    op.create_index('ix_evidence_run_grounding', 'evidence', ['run_id', 'grounding', 'authority_tier'], unique=False, schema='research')
    op.create_table('gap_report',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('loop_index', sa.SmallInteger(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('run_id', 'loop_index'),
    schema='research'
    )
    op.create_table('node_event',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('node', sa.Text(), nullable=False),
    sa.Column('loop_index', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='research'
    )
    op.create_index('ix_node_event_run_started', 'node_event', ['run_id', 'started_at'], unique=False, schema='research')
    op.create_table('raw_result',
    sa.Column('raw_id', sa.Text(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('url_canonical', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('provider_rank', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('raw_id'),
    schema='research'
    )
    op.create_index('ix_raw_result_run_url', 'raw_result', ['run_id', 'url_canonical'], unique=False, schema='research')
    op.create_table('research_plan',
    sa.Column('plan_id', sa.Text(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('loop_index', sa.SmallInteger(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('plan_id'),
    schema='research'
    )
    op.create_table('research_run',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('jurisdiction', sa.Text(), nullable=False),
    sa.Column('request', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('loop_index', sa.SmallInteger(), nullable=False),
    sa.Column('verdict', sa.Text(), nullable=True),
    sa.Column('budget_inr', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('spent_inr', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('run_id'),
    schema='research'
    )
    op.create_table('run_metric',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('run_id', 'name'),
    schema='research'
    )
    op.create_table('search_query',
    sa.Column('query_id', sa.Text(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('loop_index', sa.SmallInteger(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('query_id', 'run_id', 'provider'),
    schema='research'
    )
    op.create_index('ix_search_query_run', 'search_query', ['run_id'], unique=False, schema='research')
    op.create_table('source',
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('url_canonical', sa.Text(), nullable=False),
    sa.Column('fetch_url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('doi', sa.Text(), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.Column('court_level', sa.Text(), nullable=False),
    sa.Column('issuing_body', sa.Text(), nullable=True),
    sa.Column('jurisdiction', sa.Text(), nullable=False),
    sa.Column('published_on', sa.Date(), nullable=True),
    sa.Column('citation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tier', sa.SmallInteger(), nullable=False),
    sa.Column('score', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('discovered_by', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('source_id', 'run_id'),
    schema='research'
    )
    op.create_index('ix_source_run_status_tier', 'source', ['run_id', 'status', 'tier'], unique=False, schema='research')
    op.create_table('source_document',
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('url_canonical', sa.Text(), nullable=False),
    sa.Column('mime', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('extraction_method', sa.Text(), nullable=False),
    sa.Column('extraction_confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('is_quotable', sa.Boolean(), nullable=False),
    sa.Column('paragraph_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('content_hash'),
    schema='research'
    )
    op.create_index('ix_source_document_url', 'source_document', ['url_canonical', 'fetched_at'], unique=False, schema='research')
    op.create_table('source_document_link',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('run_id', 'source_id'),
    schema='research'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_document_link', schema='research')
    op.drop_index('ix_source_document_url', table_name='source_document', schema='research')
    op.drop_table('source_document', schema='research')
    op.drop_index('ix_source_run_status_tier', table_name='source', schema='research')
    op.drop_table('source', schema='research')
    op.drop_index('ix_search_query_run', table_name='search_query', schema='research')
    op.drop_table('search_query', schema='research')
    op.drop_table('run_metric', schema='research')
    op.drop_table('research_run', schema='research')
    op.drop_table('research_plan', schema='research')
    op.drop_index('ix_raw_result_run_url', table_name='raw_result', schema='research')
    op.drop_table('raw_result', schema='research')
    op.drop_index('ix_node_event_run_started', table_name='node_event', schema='research')
    op.drop_table('node_event', schema='research')
    op.drop_table('gap_report', schema='research')
    op.drop_index('ix_evidence_run_grounding', table_name='evidence', schema='research')
    op.drop_table('evidence', schema='research')
    op.drop_index('ix_api_call_log_run_provider', table_name='api_call_log', schema='research')
    op.drop_table('api_call_log', schema='research')
    # ### end Alembic commands ###
